name: Prebuild

on:
  release:
    types: [created]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

          - name: Install Node.js dependencies
        run: npm install --ignore-scripts

      # ШАГ 1: Собрать артефакт в стандартную для prebuildify папку
      - name: Build native addon
        run: npm run build

      # ШАГ 2: Сказать prebuildify упаковать то, что уже лежит в стандартной папке
      - name: Package with Prebuildify
        run: npm run prebuild

      - name: Upload prebuilds to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'prebuilds/*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}