name: Release Prebuilds (Windows Only)

on:
  release:
    types: [created]

jobs:
  build-and-upload-windows:
    name: Build and Upload for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # 1. Просто компилируем Rust проект. Никаких npm.
      - name: Build native addon with Cargo
        run: cargo build --release --manifest-path native/Cargo.toml

      # 2. Вручную создаем папки и копируем файл
      - name: Stage addon for packaging
        shell: bash
        run: |
          # Создаем папки, куда будем класть файл
          mkdir -p build/Release
          # Копируем скомпилированный файл из стандартного пути Cargo в наш
          # На Windows он называется .dll
          cp native/target/release/rustcatch.dll build/Release/addon.node

      # 3. Вручную упаковываем в архив
      - name: Manually package the addon
        shell: bash
        run: |
          cd build/Release
          mkdir -p ../../prebuilds
          tar -czvf ../../prebuilds/rustcatch-v${{ github.ref_name }}-node-v108-win32-x64.tar.gz addon.node

      # 4. Загружаем архив
      - name: Upload prebuilds to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'prebuilds/*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}