name: Release Prebuilds (Windows Only)

on:
  release:
    types: [created]

jobs:
  build-and-upload-windows:
    name: Build and Upload for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Node.js dependencies
        run: npm install --ignore-scripts

      - name: Build native addon
        run: npx cargo-cp-artifact -nc build/Release/addon.node -- cargo build --release --manifest-path native/Cargo.toml --message-format=json-render-diagnostics

      - name: Package with Prebuildify
        run: npx prebuildify --strip -t 18.0.0

      - name: Upload prebuilds to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'prebuilds/*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}